image: ubuntu:18.04
services:
    - docker:dind

stages:
    - build
    - test

build:
    stage: build
    image: docker:19.03.1
    script:
        - docker build -t smart-ad .

test:
    stage: test
    before_script:
        - apt-get update
        - apt-get -y install python3-pip
        - apt-get -y install python3-psycopg2
        - apt-get install -y python-lasagne
        - pip3 install -r requirements.txt
    script:
        - pytest tests.py